plugins {
    alias(libs.plugins.shadow)
    id 'java-library'
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

dependencies {
    implementation project(':common')

    compileOnly 'net.minestom:minestom:2026.09.12-26.2'
    compileOnly 'org.slf4j:slf4j-api:2.0.19'

    api 'com.google.code.gson:gson:2.11.0'

    // Required dependencies:
    implementation 'org.yaml:snakeyaml:2.0'
}

shadowJar {
    archiveFileName = "LuckPerms-Minestom-${project.ext.fullVersion}.jar"

//    dependencies {
//        include(dependency('net.luckperms:.*'))
//        include(dependency('me.lucko.luckperms:.*'))
//    }

    relocate 'net.kyori.adventure', 'me.lucko.luckperms.lib.adventure'
    relocate 'net.kyori.event', 'me.lucko.luckperms.lib.eventbus'
    relocate 'net.kyori.option', 'me.lucko.luckperms.lib.option'
    relocate 'com.github.benmanes.caffeine', 'me.lucko.luckperms.lib.caffeine'
    relocate 'okio', 'me.lucko.luckperms.lib.okio'
    relocate 'okhttp3', 'me.lucko.luckperms.lib.okhttp3'
    relocate 'net.bytebuddy', 'me.lucko.luckperms.lib.bytebuddy'
    relocate 'me.lucko.commodore', 'me.lucko.luckperms.lib.commodore'
//    relocate 'org.mariadb.jdbc', 'me.lucko.luckperms.lib.mariadb'
//    relocate 'com.mysql', 'me.lucko.luckperms.lib.mysql'
//    relocate 'org.postgresql', 'me.lucko.luckperms.lib.postgresql'
//    relocate 'com.zaxxer.hikari', 'me.lucko.luckperms.lib.hikari'
//    relocate 'com.mongodb', 'me.lucko.luckperms.lib.mongodb'
//    relocate 'org.bson', 'me.lucko.luckperms.lib.bson'
//    relocate 'redis.clients.jedis', 'me.lucko.luckperms.lib.jedis'
//    relocate 'io.nats.client', 'me.lucko.luckperms.lib.nats'
//    relocate 'com.rabbitmq', 'me.lucko.luckperms.lib.rabbitmq'
//    relocate 'org.apache.commons.pool2', 'me.lucko.luckperms.lib.commonspool2'
//    relocate 'ninja.leaping.configurate', 'me.lucko.luckperms.lib.configurate'
    relocate 'org.yaml.snakeyaml', 'me.lucko.luckperms.lib.yaml'
}

artifacts {
    archives shadowJar
}

publishing {
    repositories {
        mavenLocal()
    }

    publications {
        mavenJava(MavenPublication) {
            artifactId = 'luckperms-minestom'

            from components.java

            pom {
                name = 'LuckPerms Minestom'
                description = 'A permissions plugin for Minestom servers.'
                url = 'https://github.com/ImTheLion/LuckPerms'

                licenses {
                    license {
                        name = 'MIT'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'lucko'
                        name = 'Luck'
                        url = 'https://lucko.me'
                        email = 'git@lucko.me'
                    }
                }

                scm {
                    connection = 'scm:git:https://github.com/ImTheLion/LuckPerms.git'
                    developerConnection = 'scm:git:git@github.com:ImTheLion/LuckPerms.git'
                    url = 'https://github.com/ImTheLion/LuckPerms'
                }

                issueManagement {
                    system = 'GitHub'
                    url = 'https://github.com/ImTheLion/LuckPerms/issues'
                }
            }
        }
    }
}
